- name: Copy .bashrc
  template: 
    src=bashrc.j2
    dest=/home/vagrant/.bashrc
    force=yes
- name: Copy .vimrc
  template: 
    src=vimrc.j2
    dest=/home/vagrant/.vimrc
    force=yes
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=360000
- name: Install basic packages
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - vim-gtk
    - git 
    - subversion 
    - realpath 
    - cmake 
- name: Install python packages
  apt: name={{ item }} state=present
  with_items:
    - python-pip
    - libyaml-dev
    - ipython

